spring:
  application:
    name: analytics-microservice

  kafka:
#    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

server:
  port: 1214

logging:
  level:
    org.springframework.kafka: DEBUG